apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager # Default namespace for cert-manager

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: "v1.14.5" # Use a specific, recent version
  releaseName: cert-manager
  namespace: cert-manager # Deploy into its own namespace
  # Include CRDs required by cert-manager
  includeCRDs: true
  valuesInline:
    installCRDs: true # Another way to ensure CRDs are installed
    # Add any specific values needed for your environment
    # For example, if using a specific ingress controller or DNS provider
